### ISSUE TITLE
SDL 2.0.0 Backwards-compatability

### ISSUE THREAD

**Issue by Tangent128** [Tangent128/luasdl2#12]
When support for 2.0.1 features was added, compiling against SDL 2.0.0 stopped working; if feasible, add compile-time checks to support SDL 2.0.0 again.

**Comment by Web-eWorks** [comment]
2.0.0 and 2.0.1 were released two months apart back in 2013, it is now almost 2017.  I think it would be more hassle than gain at this point.

**Comment by Tangent128** [comment]
Will ignore 2.0.0 unless and until a real-world bug report comes in, then.
