### ISSUE TITLE
how to install Lua on Ubuntu?

### ISSUE THREAD

**Issue by Murii** [Tangent128/luasdl2#13]
Hello.I've been trying to install Lua using sudo apt-get install liblua5.2-0 and it worked but when I used Cmake 3.2.0 for building luasdl2 it told me I need to download it

**Comment by Tangent128** [comment]
1. Can you post the literal error you saw?
2. What happens if you type "lua" at the command prompt?

**Comment by Murii** [comment]
I just fixed it installing liblua-dev version.
