### ISSUE TITLE
What happens after building luasdl2?

### ISSUE THREAD

**Issue by Murii** [Tangent128/luasdl2#14]
I manage to build luasdl2 and I got SDL.so and the rests of .so libs.I tried running an example linking sublime with SDL.so but it wont start the example.How should I make it?

**Comment by Tangent128** [comment]
I would need to see the example you are referring to and/or the error you are getting;

but as a guess, are the .so files located where Lua can find them? Search for documentation on LUA_CPATH, such as http://www.lua.org/manual/5.2/manual.html#pdf-package.cpath

**Comment by Tangent128** [comment]
Closed for inactivity; please comment if you still need assistance.
