### ISSUE TITLE
LuaDist

### ISSUE THREAD

**Issue by Tangent128** [Tangent128/luasdl2#31]
> Hello,
> 
> I have just a little question: Could you offer your bindings for LuaSDL2 on LuaDIST?
> (If you want to investigate: have a look at http://luadist.org/ and in the  "Links"-section have a look at "How to contribute")
> 
> Thanks for an answer in advance
> tDwtp

**Comment by markand** [comment]
LuaDist is no longer under development so there won't be any reason to create a package for it.
