### ISSUE TITLE
renderer:copyEx doesn't accept textures

### ISSUE THREAD

**Issue by MadPie** [Tangent128/luasdl2#40]
The function errors saying it expected a table, instead of userdata for arg 1, which is the texture. Is there a fix for this?

Here is the error-

`bad argument #1 to 'copyEx' (table expected, got userdata)`

**Comment by Tangent128** [comment]
copyEx takes its arguments in the form of a table.

Instead of 

    renderer:copyEx(textureUserdata)

try

    renderer:copyEx({texture = textureUserdata})

[(Documentation)](https://github.com/Tangent128/luasdl2/wiki/Sdl-RendererCopyEx)

**Comment by MadPie** [comment]
That fixed it.
