### ISSUE TITLE
[Question] How to share ?

### ISSUE THREAD

**Issue by MangelMaxime** [Tangent128/luasdl2#47]
Hello,
I just discovered this repo and I am interested in using it but I have a question.

How can we share a game made with luasdl2 ? Is this possible to create some sort of installer ? Or self containing folder ?

**Comment by Tangent128** [comment]
The particulars are outside the scope of this project, and there are probably far more complete resources available elsewhere, but you can package up a Lua application into a folder, yes.

I believe you'll need to include:
- the Lua interpreter (and libraries if it needs them)
- the luasdl libraries (with correct folder structure to make imports work)
- your code (same note re: fodler structure)
- the SDL libraries
- any other libraries you might use
- a launch script to set the right search paths.

If on Linux or OSX, read up on LD_LIBRARY_PATH and ldd. On any system, read up on how Lua searches for modules.

**Comment by MangelMaxime** [comment]
Hum, ok. So the idea is the package all the libraries and lua requirement in one folder. Thanks for the information :)
