### ISSUE TITLE
Possible Versioning Change

### ISSUE THREAD

**Issue by Web-eWorks** [Tangent128/luasdl2#58]
(Continuing on from discussion on #57).

How about 'Ver. x.x(.x), for SDL 2.0.1 - 2.0.5'?  As there's at least some effort for backwards compatibility going on, having the latest SDL version in the main version number seems counter-intuitive.

Something I would additionally like to see would be a unified set of guidelines for what increments which version digit, perhaps even adopting the [SemVer](semver.org) standard.

At some point, to facilitate added functionality, I may want to try to move the `obj:getWhatever()` interface to a `obj.whatever` implicit-getter style interface (probably using [lstruct](https://gitlab.com/axtel-sturnclaw/lstruct), once I get the C API production-ready).  A big 'Breaking Changes' number to increment would be a virtual necessity with those kinds of changes.

**Comment by hishamhm** [comment]
Please also update the rockspec in luarocks.org :) Should I add a separate issue for this?

**Comment by Web-eWorks** [comment]
@Tangent128 has already been notified, so an additional issue is probably not necessary.

Any versioning scheme changes would take place after the rockspec has been updated to the latest changes.

**Comment by Tangent128** [comment]
(Rockspec has been uploaded. Please open issues for any regressions.)
