### ISSUE TITLE
Web export? 

### ISSUE THREAD

**Issue by egordorichev** [Tangent128/luasdl2#70]
Hey guys! The project is so awesome. I love both Lua and SDL2, but I can't see any C code anymore after working in Lua for a while. I really love LOVE2d engine, but looking for a replacement, because it doesn't properly support HTML5 export. The question is: this should compile into HTML5, shouldn't it? 

Could I kindly ask you to add a script or something for that? That would be AWESOME! This project has a big future! I totally want to use it for all my next Lua projects <3

Thanks, Egor.

**Comment by Tangent128** [comment]
In theory, it might be possible to hack something together with [emscripten](https://kripken.github.io/emscripten-site/) to compile a Lua interpreter and Lua-SDL together, but it would not be something I'd want to try maintaining. (though if the patches to make it work are simple I'd consider merging them)

https://github.com/ghoulsblade/love-webplayer might be worth a look for your usecase? There are also a few Lua-to-Javascript compiler projects out there if you don't mind writing adaptors for the HTML canvas & audio APIs.
