### ISSUE TITLE
channel first/last method results in deadlock

### ISSUE THREAD

**Issue by fastcoding** [Tangent128/luasdl2#78]
I always got deadlock when use channel.first/push/pop. noticed that there might be issue with the codes.
```
static const Variant *
channelFirst(const Channel *c)
{
	Variant *v;

	SDL_LockMutex(c->mutex);
	if (STAILQ_EMPTY(&c->queue))
		return NULL;   //<---- here return without unlock mutex ???

	v = STAILQ_FIRST(&c->queue);
	SDL_UnlockMutex(c->mutex);

	return v;
}
```

**Comment by markand** [comment]
Good catch, I'll address a fix but I'm unsure if I'll keep the thread/channel API because I think they don't belong to the SDL library and there are other Lua modules for real threads.

**Comment by markand** [comment]
Oh, nevermind it was already fixed.
