### ISSUE TITLE
Compiling on OSX Bug Sur (Intel)

### ISSUE THREAD

**Issue by PeterHickman** [Tangent128/luasdl2#87]
Using luarocks to install lua-sdl2 and I am hitting an issue

```
/usr/local/include/SDL2/SDL_platform.h:87:3: error: SDL for Mac OS X only supports deploying on 10.6 and above.
# error SDL for Mac OS X only supports deploying on 10.6 and above.
```

Nuking line 87 allows the build to complete but with ton of warnings `Building for Intel with Mac OS X Deployment Target < 10.4 is invalid` and `was built for newer macOS version (10.5) than being linked (10.1)`

A quick test with some example scripts shows that it seems to be working

Is this the build process not being set up correctly for Big Sur or are the Apple development tools not ready yet

**Comment by Tangent128** [comment]
I have not been able to maintain luasdl2 for quite some time, so any changes that would need to be made for Big Sur have not been made, indeed.

**Comment by PeterHickman** [comment]
Oh, I understand. Thanks for your work on the project. Despite the warnings
it does seem to compile and work on Big Sur for both Intel and Apple Silicon

I will dig some more

**Comment by markand** [comment]
I think the problem comes from LuaRocks because the default installation of LuaRocks specify some CFLAGS that are too old. If you compile from CMake you don't get any error.

I've myself changed the luarocks configuration to look like this:

```
markand@lotus ~ $ cat /usr/local/etc/luarocks/config-5.3.lua 
-- LuaRocks configuration

rocks_trees = {
   { name = "user", root = home .. "/.luarocks" };
   { name = "system", root = "/usr/local" };
}
lua_interpreter = "lua5.3";
variables = {
	LUA_DIR = "/usr/local/opt/lua";
	LUA_BINDIR = "/usr/local/opt/lua/bin";
	CC = "export MACOSX_DEPLOYMENT_TARGET=11.0; cc ",
	LD = "export MACOSX_DEPLOYMENT_TARGET=11.0; cc "
}
```

I think the issue is up to LuaRocks only.

**Comment by PeterHickman** [comment]
Thanks for looking into this. It's working fine for me as I slowly learn
how to write some small games

Again, thank you
