### ISSUE TITLE
Missing functions?

### ISSUE THREAD

**Issue by EmperorPenguin18** [Tangent128/luasdl2#90]
I'm currently working on a project that uses this library, and the guides I'm using require these two functions:

https://wiki.libsdl.org/SDL_Vulkan_GetInstanceExtensions
https://wiki.libsdl.org/SDL_Vulkan_CreateSurface

But I can't find them in the API documentation. Are these available with this library? If not is it difficult to add them?

**Comment by Tangent128** [comment]
1) They are not; this library has not been updated to wrap the newer SDL2 calls

2) It should not be difficult to add the Vulkan functions (Lua extensions are easy to write, and the luasdl2 codebase has a lot of helpers), but my time for maintenance has been severely limited lately. (Also, you would need to find another library to actually _use_ the Vulkan API)

**Comment by EmperorPenguin18** [comment]
This is the library I'm using for the Vulkan API: https://github.com/stetre/moonvulkan

I have never written a Lua extension before (in fact I'm completely new to Lua). Is there a guide or tutorial to get me started? I already know C, so it's just the binding to Lua part I need to learn. I can't promise I'll get something working, but it might be an interesting learning opportunity I can work on if I have some free time.

**Comment by Tangent128** [comment]
If you're interested, the Lua manual is pretty well-written and concise for the amount of information it covers: http://www.lua.org/manual/

The sections about the Lua stack and `lua_pushcfunction` are good starting points.

**Comment by EmperorPenguin18** [comment]
Are there compiling instructions somewhere? I'm getting this error: `/usr/local/lib/lua/SDL.so: undefined symbol: lua_getiuservalue` and I'm pretty sure it has something to do with linking the wrong Lua version.

**Comment by EmperorPenguin18** [comment]
I have created a pull request that solves this issue. Please let me know if there are any changes you want before merge.
